### ISSUE TITLE
LessChrome HD shows on websites using new FullScreen API

### ISSUE THREAD

**Issue by jrub** [mozilla/prospector#664]
Just go to youtube, load an HTML5 video (you have to activate the HTML5 Trial on http://www.youtube.com/html5) and press the fullscreen button. The address bar is shown.

**Comment by AloisJanicek** [comment]
This add-on FF Fullscreen https://addons.mozilla.org/en-US/firefox/addon/FF_Fullscreen/ can be used as temporary solution and hopefully also as a code inspiration. But be aware, it has nasty bug which makes Firefox randomly go fullscreen. Someone in comments/reviews already provided step-by-step solution to fix this.
(I am leaving this here because with Firefox version 36 everybody will have HTML5-only YouTube by default and many people will seek solution to this LessChrome HD issue)
